### ISSUE TITLE
Video is gone

### ISSUE THREAD

**Issue by MostHated** [kamindustries/Dust#2]
Hello,
    I wanted to take a look but the video is gone. Perhaps upload to youtube? All the videos I went to look at recently that were on Twitch were all saying they no longer were available.

Thanks,
-MH

**Comment by kamindustries** [comment]
D'oh. I thought I did the thing on twitch where it would save it. Thanks, I updated the readme with a link to youtube:
https://youtu.be/h9JKPuK_LAo

**Comment by MostHated** [comment]
Awesome, thanks for that. I was going to just download it so I could check it out, but when I did I had some issues at the time, I can't recall what it was off hand though, lol, so that doesn't help. I will have to download it and try again.
